# The name of this app. Must be unique within a project.
name: app

type: php:8.2

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - pdo_pgsql
        

# Relationships enable access from this app to a given service.
relationships:
    database: "database:postgresql"


#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: config/preload.php

build:
    flavor: none

# The size of the persistent disk of the application (in MB).
disk: 2048

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

workers:
    messenger:
        # PHP background workers usually don't require much CPU. See
        # https://symfony.com/doc/current/cloud/cookbooks/resources_allocation.html
        # for more information
        size: XS
        resources:
            base_memory: 64 # Keep in sync with the `memory-limit` flag value
            memory_ratio: 128
        commands:
            # Don't forget to update your receiver name(s)
            start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
    "/var": { source: local, source_path: var }
    '/public/assets/image_product':
        source: local
        source_path: uploads
    

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e

        symfony-deploy
